---
name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build compliance-masonry
        run: make build

      - name: Run tests
        run: |
          go test -covermode=count -coverprofile=coverage.txt ./...
          go tool cover -func coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          file: ./coverage.txt
